---
# Post tasks

- name: Perform YUM package cleanup
  package:
    autoremove: true
  changed_when: no
  ignore_errors: yes
  tags:
  - skip_ansible_lint
  vars:
    ansible_python_interpreter: /bin/python

- name: "AUTOMATED | 4.2.4 | PATCH | Ensure permissions on all logfiles are configured"
  command: find /var/log -type f -exec chmod g-wx,o-rwx "{}" + -o -type d -exec chmod g-wx,o-rwx "{}" +
  changed_when: no
  failed_when: no
  when:
  - amznlnx2cis_rule_4_2_3
  tags:
  - level1
  - patch
  - automated
  - rule_4.2.4
