---

- name: "SCORED | 5.5.2 | PATCH | Ensure system accounts are secured"
  block:
  - name: "SCORED | 5.5.2 | PATCH | Ensure system accounts are secured | Set nologin"
    user:
      name: "{{ item.id }}"
      shell: /usr/sbin/nologin
    loop: "{{ amznlnx2cis_passwd }}"
    become: true
    when:
    - item.id != "root"
    - item.id != "sync"
    - item.id != "shutdown"
    - item.id != "halt"
    - item.gid < amznlnx2cis_int_gid
    - item.shell != "      /bin/false"
    - item.shell != "      /usr/sbin/nologin"

  - name: "SCORED | 5.5.2 | PATCH | Ensure system accounts are secured | Lock accounts"
    user:
      name: "{{ item.id }}"
      password_lock: true
    loop: "{{ amznlnx2cis_passwd }}"
    become: true
    when:
    - item.id != "halt"
    - item.id != "shutdown"
    - item.id != "sync"
    - item.id != "root"
    - item.gid < amznlnx2cis_int_gid
    - item.shell != "      /bin/false"
    - item.shell != "      /usr/sbin/nologin"
  when:
  - amznlnx2cis_rule_5_5_2
  tags:
  - level1
  - patch
  - rule_5.5.2

- name: "SCORED | 5.5.3 | PATCH | Ensure default group for the root account is GID 0"
  command: usermod -g 0 root
  changed_when: no
  failed_when: no
  when:
  - amznlnx2cis_rule_5_5_3
  tags:
  - level1
  - patch
  - rule_5.5.3

- name: "SCORED | 5.5.4 | PATCH | Ensure default user shell timeout is configured"
  blockinfile:
    create: yes
    mode: 0644
    dest: "{{ item.dest }}"
    state: "{{ item.state }}"
    marker: "# {mark} ANSIBLE MANAGED"
    block: |
      # Set session timeout - CIS ID AMZN LNX 2-5.5.4
      TMOUT={{ amznlnx2cis_shell_session_timeout.timeout }}
      readonly TMOUT
      export TMOUT
  loop:
  - dest: "{{ amznlnx2cis_shell_session_timeout.file }}"
    state: present
  - dest: /etc/profile
    state: "{{ (amznlnx2cis_shell_session_timeout.file == '/etc/profile') | ternary('present', 'absent') }}"
  when:
  - amznlnx2cis_rule_5_5_4
  tags:
  - level2
  - patch
  - rule_5.5.4

- name: "SCORED | 5.5.5 | PATCH | Ensure default user umask is configured"
  block:
  - name: "SCORED | 5.5.5 | PATCH | Ensure default user umask is configured | Set umask for /etc/bashrc"
    replace:
      path: /etc/bashrc
      regexp: '(^\s+umask) 002'
      replace: '\1 027'

  - name: "SCORED | 5.5.5 | PATCH | Ensure default user umask is configured | Set umask for /etc/profile"
    replace:
      path: /etc/profile
      regexp: '(^\s+umask) 002'
      replace: '\1 027'
  when:
  - amznlnx2cis_rule_5_5_5
  tags:
  - level1
  - patch
  - rule_5.5.5
