---

- name: "SCORED | 5.3.1 | PATCH | Ensure permissions on /etc/ssh/sshd_config are configured"
  file:
    dest: /etc/ssh/sshd_config
    state: file
    owner: root
    group: root
    mode: 0600
  when:
  - amznlnx2cis_rule_5_3_1
  tags:
  - level1
  - patch
  - ssh
  - rule_5.3.1

- name: "SCORED | 5.3.2 | PATCH | Ensure permissions on SSH private host key files are configured"
  block:
  - name: "SCORED | 5.3.2 | AUDIT | Ensure permissions on SSH private host key files are configured"
    find:
      paths:
      - /etc/ssh
      patterns: 'ssh_host_*_key'
      recurse: true
      file_type: any
    register: amznlnx2_5_3_2_priv_results

  - name: "SCORED | 5.3.2 | AUDIT | Ensure permissions on SSH private host key files are configured"
    file:
      path: "{{ item.path }}"
      owner: root
      group: root
      mode: 0600
    loop: "{{ amznlnx2_5_3_2_priv_results.files }}"
  when:
  - amznlnx2cis_rule_5_3_2
  tags:
  - level1
  - patch
  - ssh
  - rule_5.3.2

- name: "SCORED | 5.3.3 | PATCH | Ensure permissions on SSH public host key files are configured"
  block:
  - name: "SCORED | 5.3.3 | AUDIT | Ensure permissions on SSH public host key files are configured"
    find:
      paths:
      - /etc/ssh
      patterns: 'ssh_host_*_key'
      recurse: true
      file_type: any
    register: amznlnx2_5_3_3_pub_results

  - name: "SCORED | 5.3.3 | AUDIT | Ensure permissions on SSH public host key files are configured"
    file:
      path: "{{ item.path }}"
      owner: root
      group: root
      mode: 0600
    loop: "{{ amznlnx2_5_3_3_pub_results.files }}"
  when:
  - amznlnx2cis_rule_5_3_3
  tags:
  - level1
  - patch
  - ssh
  - rule_5.3.3


- name: "SCORED | 5.3.4 | PATCH | Ensure SSH access is limited"
  block:
  - name: "SCORED | 5.3.4 | PATCH | Ensure SSH access is limited | Add line to sshd_config for allowusers"
    lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: "^AllowUsers"
      line: AllowUsers {{ amznlnx2cis_sshd['allowusers'] }}
    notify:
    - restart sshd
    when:
    - "amznlnx2cis_sshd['allowusers']|default('') | length > 0"

  - name: "SCORED | 5.3.4 | PATCH | Ensure SSH access is limited | Add line to sshd_config for allowgroups"
    lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: "^AllowGroups"
      line: AllowGroups {{ amznlnx2cis_sshd['allowgroups'] }}
    notify:
    - restart sshd
    when:
    - "amznlnx2cis_sshd['allowgroups']|default('') | length > 0"

  - name: "SCORED | 5.3.4 | PATCH | Ensure SSH access is limited | Add line to sshd_config for denyusers"
    lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: "^DenyUsers"
      line: DenyUsers {{ amznlnx2cis_sshd['denyusers'] }}
    notify:
    - restart sshd
    when:
    - "amznlnx2cis_sshd['denyusers']|default('') | length > 0"

  - name: "SCORED | 5.3.4 | PATCH | Ensure SSH access is limited | Add line to sshd_config for denygroups"
    lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: "^DenyGroups"
      line: DenyGroups {{ amznlnx2cis_sshd['denygroups'] }}
    notify:
    - restart sshd
    when:
    - "amznlnx2cis_sshd['denygroups']|default('') | length > 0"
  when:
  - amznlnx2cis_rule_5_3_4
  tags:
  - level1
  - patch
  - ssh
  - rule_5.3.4


- name: "SCORED | 5.3.5 | PATCH | Ensure SSH LogLevel is appropriate"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: "^#LogLevel|^LogLevel"
    line: 'LogLevel {{ amznlnx2cis_ssh_loglevel }}'
  notify:
  - restart sshd
  when:
  - amznlnx2cis_rule_5_3_5
  tags:
  - level1
  - patch
  - ssh
  - rule_5.3.5

- name: "SCORED | 5.3.6 | PATCH | Ensure SSH X11 forwarding is disabled"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: "^#X11Forwarding|^X11Forwarding"
    line: 'X11Forwarding no'
  notify:
  - restart sshd
  when:
  - amznlnx2cis_rule_5_3_6
  tags:
  - level1
  - level2
  - patch
  - ssh
  - rule_5.3.6

- name: "SCORED | 5.3.7 | PATCH | Ensure SSH MaxAuthTries is set to 4 or less"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '^(#)?MaxAuthTries \d'
    line: 'MaxAuthTries 4'
  notify:
  - restart sshd
  when:
  - amznlnx2cis_rule_5_3_7
  tags:
  - level1
  - patch
  - ssh
  - rule_5.3.7

- name: "SCORED | 5.3.8 | PATCH | Ensure SSH IgnoreRhosts is enabled"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: "^#IgnoreRhosts|^IgnoreRhosts"
    line: 'IgnoreRhosts yes'
  notify:
  - restart sshd
  when:
  - amznlnx2cis_rule_5_3_8
  tags:
  - level1
  - patch
  - ssh
  - rule_5.3.8

- name: "SCORED | 5.3.9 | PATCH | Ensure SSH HostbasedAuthentication is disabled"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: ^#HostbasedAuthentication|^HostbasedAuthentication"
    line: 'HostbasedAuthentication no'
  notify:
  - restart sshd
  when:
  - amznlnx2cis_rule_5_3_9
  tags:
  - level1
  - patch
  - ssh
  - rule_5.3.9

- name: "SCORED | 5.3.10 | PATCH | Ensure SSH root login is disabled"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: "^#PermitRootLogin|^PermitRootLogin"
    line: 'PermitRootLogin no'
  notify:
  - restart sshd
  when:
  - amznlnx2cis_rule_5_3_10
  tags:
  - level1
  - patch
  - ssh
  - rule_5.3.10

- name: "SCORED | 5.3.11 | PATCH | Ensure SSH PermitEmptyPasswords is disabled"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: "^#PermitEmptyPasswords|^PermitEmptyPasswords"
    line: 'PermitEmptyPasswords no'
  notify:
  - restart sshd
  when:
  - amznlnx2cis_rule_5_3_11
  tags:
  - level1
  - patch
  - ssh
  - rule_5.3.11

- name: "SCORED | 5.3.12 | PATCH | Ensure SSH PermitUserEnvironment is disabled"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: "^#PermitUserEnvironment|^PermitUserEnvironment"
    line: 'PermitUserEnvironment no'
  notify:
  - restart sshd
  when:
  - amznlnx2cis_rule_5_3_12
  tags:
  - level1
  - patch
  - ssh
  - rule_5.3.12

- name: "SCORED | 5.3.13 | PATCH | Ensure only strong Ciphers are used"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '^Cipherss'
    line: "Ciphers {{ amznlnx2cis_sshd['ciphers'] }}"
  notify:
  - restart sshd
  when:
  - amznlnx2cis_rule_5_3_13
  tags:
  - level1
  - patch
  - ssh
  - rule_5.3.13

- name: "SCORED | 5.3.14 | PATCH | Ensure only approved MAC algorithms are used"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '^MACs'
    line: "MACs {{ amznlnx2cis_sshd['macs'] }}"
  notify:
  - restart sshd
  when:
  - amznlnx2cis_rule_5_3_14
  tags:
  - level1
  - patch
  - ssh
  - rule_5.3.14

- name: "SCORED | 5.3.15 | PATCH | Ensure only strong Key Exchange algorithms are used"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '^KexAlgorithms'
    line: "KexAlgorithms {{ amznlnx2cis_sshd['kex'] }}"
  notify:
  - restart sshd
  when:
  - amznlnx2cis_rule_5_3_15
  tags:
  - level1
  - patch
  - ssh
  - rule_5.3.15

- name: "SCORED | 5.3.16 | PATCH | Ensure SSH Idle Timeout Interval is configured"
  block:
  - name: "SCORED | 5.3.16 | PATCH | Ensure SSH Idle Timeout Interval is configured | Add line in sshd_config for ClientAliveInterval"
    lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^ClientAliveInterval'
      line: "ClientAliveInterval {{ amznlnx2cis_sshd['clientaliveinterval'] }}"
    notify:
    - restart sshd

  - name: "SCORED | 5.3.16 | PATCH | Ensure SSH Idle Timeout Interval is configured | Ensure SSH ClientAliveCountMax set to <= 3"
    lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^ClientAliveCountMax'
      line: "ClientAliveCountMax {{ amznlnx2cis_sshd['clientalivecountmax'] }}"
    notify:
    - restart sshd
  when:
  - amznlnx2cis_rule_5_3_16
  tags:
  - level1
  - patch
  - ssh
  - rule_5.3.16

- name: "SCORED | 5.3.17 | PATCH | Ensure SSH LoginGraceTime is set to one minute or less"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: "^#LoginGraceTime|^LoginGraceTime"
    line: "LoginGraceTime {{ amznlnx2cis_sshd['logingracetime'] }}"
  notify:
  - restart sshd
  when:
  - amznlnx2cis_rule_5_3_17
  tags:
  - level1
  - patch
  - ssh
  - rule_5.3.17

- name: "SCORED | 5.3.18 | PATCH | Ensure SSH warning banner is configured"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '^Banner'
    line: 'Banner /etc/issue.net'
  notify:
  - restart sshd
  when:
  - amznlnx2cis_rule_5_3_18
  tags:
  - level1
  - patch
  - ssh
  - rule_5.3.18

- name: "SCORED | 5.3.19 | PATCH | Ensure SSH PAM is enabled"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: "^#UsePAM|^UsePAM"
    line: 'UsePAM yes'
  notify:
  - restart sshd
  when:
  - amznlnx2cis_rule_5_3_19
  tags:
  - level1
  - patch
  - ssh
  - rule_5.3.19

- name: "SCORED | 5.3.20 | PATCH | Ensure SSH AllowTcpForwarding is disabled"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: "^#AllowTcpForwarding|^AllowTcpForwarding"
    line: 'AllowTcpForwarding no'
  notify:
  - restart sshd
  when:
  - amznlnx2cis_rule_5_3_20
  tags:
  - level2
  - patch
  - ssh
  - rule_5.3.20

- name: "SCORED | 5.3.21 | PATCH | Ensure SSH MaxStartups is configured"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: "^#MaxStartups|^MaxStartups"
    line: 'MaxStartups 10:30:60'
  notify:
  - restart sshd
  when:
  - amznlnx2cis_rule_5_3_21
  tags:
  - level1
  - patch
  - ssh
  - rule_5.3.21

- name: "SCORED | 5.3.22 | PATCH | Ensure SSH MaxSessions is limited"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: "^#MaxSessions|^MaxSessions"
    line: 'MaxSessions {{ amznlnx2cis_ssh_maxsessions }}'
  notify:
  - restart sshd
  when:
  - amznlnx2cis_rule_5_3_22
  tags:
  - level1
  - patch
  - ssh
  - rule_5.3.22
