---

- name: "AUTOMATED | 5.2.1 | PATCH | Ensure sudo is installed"
  package:
    name: sudo
    state: present
  when:
    - amznlnx2cis_rule_5_2_1
  tags:
    - level1
    - automated
    - patch
    - rule_5.2.1

- name: "AUTOMATED | 5.2.2 | PATCH | Ensure sudo commands use pty"
  lineinfile:
    state: present
    dest: /etc/sudoers
    # regexp: '^(#)?auth\s+required\s+pam_wheel\.so'
    line: 'Defaults use_pty'
  when:
  - amznlnx2cis_rule_5_2_2
  tags:
  - level1
  - automated
  - patch
  - rule_5.2.2

- name: "AUTOMATED | 5.2.3 | PATCH | Ensure sudo log file exists"
  lineinfile:
    state: present
    dest: /etc/sudoers
    # regexp: '^(#)?auth\s+required\s+pam_wheel\.so'
    line: 'Defaults logfile="/var/log/sudo.log"'
  when:
  - amznlnx2cis_rule_5_2_3
  tags:
  - level1
  - automated
  - patch
  - rule_5.2.3
