---
# handlers file for AMZNLNX2-CIS

- name: systemd restart tmp.mount
  become: yes
  systemd:
    name: tmp.mount
    daemon_reload: yes
    enabled: yes
    masked: no
    state: reloaded

- name: remount tmp
  command: mount -o remount /tmp
  args:
    warn: false

- name: remount dev_shm
  command: mount -o remount /dev/shm
  args:
    warn: false

- name: remount var_tmp
  command: mount -o remount /var/tmp
  args:
    warn: false

- name: remount home
  command: mount -o remount /home
  args:
    warn: false

- name: grub2cfg
  command: /sbin/grub2-mkconfig -o "{{ amznlnx2cis_bootloader_file }}"

- name: restart postfix
  become: yes
  service:
    name: postfix
    state: restarted

- name: sysctl flush ipv4 route table
  become: yes
  sysctl:
    name: net.ipv4.route.flush
    value: '1'
    sysctl_set: yes
  when: ansible_virtualization_type != "docker"

- name: sysctl flush ipv6 route table
  become: yes
  sysctl:
    name: net.ipv6.route.flush
    value: '1'
    sysctl_set: yes
  when: ansible_virtualization_type != "docker"

- name: restart auditd
  command: /sbin/service auditd restart
  changed_when: no
  check_mode: no
  failed_when: no
  args:
    warn: no
  when:
  - not amznlnx2cis_skip_for_travis
  tags:
  - skip_ansible_lint

- name: restart rsyslog
  become: yes
  service:
    name: rsyslog
    state: restarted

- name: restart sshd
  become: yes
  service:
    name: sshd
    state: restarted
