---

- name: "MANUAL | 3.1.1 | PATCH | Disable IPv6 | sysctl"
  sysctl:
    name: "{{ item }}"
    value: '1'
    reload: yes
    state: present
  loop:
  - net.ipv6.conf.all.disable_ipv6
  - net.ipv6.conf.default.disable_ipv6
  when:
  - not amznlnx2cis_ipv6_required
  - amznlnx2cis_rule_3_1_1
  notify: sysctl flush ipv6 route table
  tags:
  - level2
  - rule_3.1.1
  - patch

- name: "MANUAL | 3.1.2 | Ensure wireless interfaces are disabled"
  block:
  - name: "MANUAL | 3.1.2 | PATCH | Ensure wireless interfaces are disabled | Check if nmcli command is available"
    command: rpm -q NetworkManager
    args:
      warn: no
    check_mode: no
    changed_when: no
    register: amznlnx2_nmcli_available
    failed_when: no

  - name: "MANUAL | 3.1.2 | PATCH | Ensure wireless interfaces are disabled | Check if wifi is enabled"
    command: nmcli radio wifi
    register: amznlnx2_wifi_enabled
    check_mode: no
    changed_when: amznlnx2_wifi_enabled.stdout != "disabled"
    when: amznlnx2_nmcli_available.rc == 0

  - name: "MANUAL | 3.1.2 | PATCH | Ensure wireless interfaces are disabled | Disable wifi if enabled"
    command: nmcli radio wifi off
    when: amznlnx2_wifi_enabled is changed
  when:
  - amznlnx2cis_rule_3_1_2
  tags:
  - level1
  - level2
  - rule_3.1.2
