---

- name: "AUTOMATED | 2.1.2 | PATCH | Ensure X11 Server components are not installed"
  package:
    state: absent
    name:
    - "@X Window System"
    - "xorg-x11*"
  vars:
    ansible_python_interpreter: /bin/python
  when:
  - not amznlnx2cis_xwindows_required
  - amznlnx2cis_rule_2_1_2
  tags:
  - level1
  - scored
  - xwindows
  - patch
  - rule_2.1.2

- name: "AUTOMATED | 2.1.3 | PATCH | Ensure Avahi Server is not installed | disabled"
  service:
    name: avahi-daemon
    state: stopped
    enabled: no
  when:
  - not amznlnx2cis_avahi_server
  - "'avahi' in ansible_facts.packages"
  - amznlnx2cis_rule_2_1_3
  tags:
  - level1
  - scored
  - avahi
  - services
  - patch
  - rule_2.1.3

- name: "AUTOMATED | 2.1.4 | PATCH | Ensure CUPS is not installed"
  package:
    name: cups
    state: absent
  vars:
    ansible_python_interpreter: /bin/python
  when:
  - not amznlnx2cis_cups_server
  - "'cups' in ansible_facts.packages"
  - amznlnx2cis_rule_2_1_4
  tags:
  - level1
  - scored
  - cups
  - services
  - patch
  - rule_2.1.4

- name: "AUTOMATED | 2.2.5 | PATCH | Ensure DHCP Server is not enabled"
  package:
    name: dhcpd
    state: absent
  vars:
    ansible_python_interpreter: /bin/python
  when:
  - not amznlnx2cis_dhcp_server
  - "'dhcp' in ansible_facts.packages"
  - amznlnx2cis_rule_2_1_5
  tags:
  - level1
  - scored
  - dhcp
  - services
  - patch
  - rule_2.1.5

- name: "AUTOMATED | 2.1.6 | PATCH | Ensure LDAP server is not installed"
  package:
    name: openldap-servers
    state: absent
  vars:
    ansible_python_interpreter: /bin/python
  when:
  - not amznlnx2cis_ldap_server
  - "'openldap-servers' in ansible_facts.packages"
  - amznlnx2cis_rule_2_1_6
  tags:
  - level1
  - scored
  - ldap
  - services
  - patch
  - rule_2.1.6

- name: "AUTOMATED | 2.1.7 | PATCH | Ensure dns server is not installed"
  package:
    name: named
    state: absent
  vars:
    ansible_python_interpreter: /bin/python
  when:
  - not amznlnx2cis_named_server
  - "'bind' in ansible_facts.packages"
  - amznlnx2cis_rule_2_1_7
  tags:
  - level1
  - scored
  - dns
  - services
  - patch
  - rule_2.1.7

- name: "AUTOMATED | 2.1.8 | PATCH | Ensure FTP server is not installed"
  package:
    name: vsftpd
    state: absent
  vars:
    ansible_python_interpreter: /bin/python
  when:
  - not amznlnx2cis_vsftpd_server
  - "'vsftpd' in ansible_facts.packages"
  - amznlnx2cis_rule_2_1_8
  tags:
  - level1
  - scored
  - ftp
  - services
  - patch
  - rule_2.1.8

- name: "AUTOMATED | 2.1.9 | PATCH | Ensure HTTP server is not installed"
  package:
    name: httpd
    state: absent
  vars:
    ansible_python_interpreter: /bin/python
  when:
  - not amznlnx2cis_httpd_server
  - "'httpd' in ansible_facts.packages"
  - amznlnx2cis_rule_2_1_9
  tags:
  - level1
  - scored
  - ldap
  - services
  - patch
  - rule_2.1.9

- name: "AUTOMATED | 2.1.10 | PATCH | Ensure IMAP and POP3 server is not installed"
  package:
    name: dovecot
    state: absent
  vars:
    ansible_python_interpreter: /bin/python
  when:
  - not amznlnx2cis_dovecot_server
  - "'dovecot' in ansible_facts.packages"
  - amznlnx2cis_rule_2_1_10
  tags:
  - level1
  - scored
  - dovecot
  - services
  - patch
  - rule_2.1.10

- name: "AUTOMATED | 2.1.11 | PATCH | Ensure Samba server is not installed"
  package:
    name: samba
    state: absent
  vars:
    ansible_python_interpreter: /bin/python
  when:
  - not amznlnx2cis_smb_server
  - "'samba' in ansible_facts.packages"
  - amznlnx2cis_rule_2_1_11
  tags:
  - level1
  - scored
  - samba
  - services
  - patch
  - rule_2.1.11

- name: "AUTOMATED | 2.1.12 | PATCH | Ensure HTTP Proxy server is not installed"
  package:
    name: squid
    state: absent
  vars:
    ansible_python_interpreter: /bin/python
  when:
  - not amznlnx2cis_squid_server
  - "'squid' in ansible_facts.packages"
  - amznlnx2cis_rule_2_1_12
  tags:
  - level1
  - scored
  - squid
  - services
  - patch
  - rule_2.1.12

- name: "AUTOMATED | 2.1.13 | PATCH | Ensure net-snmp is not installed"
  package:
    name: net-snmp
    state: absent
  vars:
    ansible_python_interpreter: /bin/python
  when:
  - not amznlnx2cis_snmp_server
  - "'net-snmp' in ansible_facts.packages"
  - amznlnx2cis_rule_2_1_13
  tags:
  - level1
  - scored
  - squid
  - services
  - patch
  - rule_2.1.13

- name: "AUTOMATED | 2.1.14 | PATCH | Ensure nis server is not installed"
  package:
    name: ypserv
    state: absent
  vars:
    ansible_python_interpreter: /bin/python
  when:
  - not amznlnx2cis_nis_server
  - "'ypserv' in ansible_facts.packages"
  - amznlnx2cis_rule_2_1_14
  tags:
  - level1
  - scored
  - nis
  - services
  - patch
  - rule_2.1.14

- name: "AUTOMATED | 2.1.15 | PATCH | Ensure telnet server is not installed"
  package:
    name: telnet-server
    state: absent
  vars:
    ansible_python_interpreter: /bin/python
  when:
  - not amznlnx2cis_telnet_server
  - "'telnet-server' in ansible_facts.packages"
  - amznlnx2cis_rule_2.1_15
  tags:
  - level1
  - scored
  - telnet
  - services
  - patch
  - rule_2.1.15

- name: "AUTOMATED | 2.1.16 | PATCH | Ensure mail transfer agent is configured for local-only mode"
  lineinfile:
    dest: /etc/postfix/main.cf
    regexp: "^(#)?inet_interfaces"
    line: "inet_interfaces = loopback-only"
  notify: restart postfix
  when:
  - not amznlnx2cis_is_mail_server
  - "'postfix' in ansible_facts.packages"
  - amznlnx2cis_rule_2_1_16
  tags:
  - level1
  - patch
  - rule_2.1.16

- name: "AUTOMATED | 2.1.17 | PATCH | Ensure nfs-utils is not installed or the nfs-server service is masked"
  block:
  - name: "AUTOMATED | 2.1.17 | PATCH | Ensure nfs-utils is not installed or the nfs-server service is masked | nfs-utils "
    package:
      name: nfs-utils
      state: absent
    vars:
      ansible_python_interpreter: /bin/python
    when:
    - not amznlnx2cis_nfs_rpc_server and not amznlnx2cis_nfs_server

  - name: "AUTOMATED | 2.1.17 | PATCH | Ensure nfs-utils is not installed or the nfs-server service is masked | nfs-server "
    systemd:
      name: nfs-server
      masked: true
    when:
    - amznlnx2cis_nfs_rpc_server and not amznlnx2cis_nfs_server
  when:
  - "'nfs-utils' in ansible_facts.packages"
  - amznlnx2cis_rule_2_1_17
  tags:
  - level1
  - scored
  - nfs
  - services
  - patch
  - rule_2.1.17

- name: "AUTOMATED | 2.1.18 | PATCH | Ensure rpcbind is not installed or the irpcbind services are masked"
  block:
  - name: "AUTOMATED | 2.1.18 | PATCH | Ensure rpcbind is not installed or the rpcbind services are masked | rpcbind"
    package:
      name: rpcbind
      state: absent
    vars:
      ansible_python_interpreter: /bin/python
    when:
    - not amznlnx2cis_nfs_rpc_server and not amznlnx2cis_rpc_server

  - name: "AUTOMATED | 2.1.18 | PATCH | Ensure rpcbind is not installed or the rpcbind services are masked | rpcbind-server"
    systemd:
      name: rpcbind
      masked: true
    when:
    - amznlnx2cis_nfs_rpc_server and not amznlnx2cis_rpc_server
  when:
  - "'rpcbind' in ansible_facts.packages"
  - amznlnx2cis_rule_2_1_18
  tags:
  - level1
  - scored
  - rpc
  - services
  - patch
  - rule_2.1.18

- name: "AUTOMATED | 2.1.19 | PATCH | Ensure rsync is not installed or the rsyncd services are masked"
  package:
    name: rsync
    state: absent
  vars:
    ansible_python_interpreter: /bin/python
  when:
  - not amznlnx2cis_rsyncd_server
  - "'rsync' in ansible_facts.packages"
  - amznlnx2cis_rule_2_1_19
  tags:
  - level1
  - scored
  - rsync
  - services
  - patch
  - rule_2.1.19
