---

- name: "\n
         AUTOMATED | 1.7.1.1 | PATCH | Ensure message of the day is configured properly\n
         AUTOMATED | 1.7.1.4 | PATCH | Ensure permissions on /etc/motd are configured"
  template:
    src: etc/motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: 0644
  when:
  - amznlnx2cis_rule_1_7_1_1
  - amznlnx2cis_rule_1_7_1_4
  tags:
  - level1
  - banner
  - patch
  - rule_1.7.1.1
  - rule_1.7.1.4

- name: "\n
         AUTOMATED | 1.7.1.2 | PATCH | Ensure local login warning banner is configured properly\n
         AUTOMATED | 1.7.1.5 | PATCH | Ensure permissions on /etc/issue are configured"
  template:
    src: etc/issue.j2
    dest: /etc/issue
    owner: root
    group: root
    mode: 0644
  when:
  - amznlnx2cis_rule_1_7_1_2
  - amznlnx2cis_rule_1_7_1_5
  tags:
  - level1
  - patch
  - rule_1.7.1.2
  - rule_1.7.1.5

- name: "\n
         AUTOMATED | 1.7.1.3 | PATCH | Ensure remote login warning banner is configured properly\n
         AUTOMATED | 1.7.1.6 | PATCH | Ensure permissions on /etc/issue.net are configured"
  template:
    src: etc/issue.net.j2
    dest: /etc/issue.net
    owner: root
    group: root
    mode: 0644
  when:
  - amznlnx2cis_rule_1_7_1_3
  - amznlnx2cis_rule_1_7_1_6
  tags:
  - level1
  - banner
  - patch
  - rule_1.7.1.3
  - rule_1.7.1.6
