---

- name: "MANUAL| 1.2.1 | PATCH | Ensure GPG keys are configured | CentOS"
  command: gpg --quiet --with-fingerprint /etc/pki/rpm-gpg/RPM-GPG-KEY-amazon-linux-{{ ansible_distribution_major_version }}

  when:
  - amznlnx2cis_rule_1_2_1
  tags:
  - level1
  - notAUTOMATED
  - patch
  - rule_1.2.1

- name: "MANUAL| 1.2.2 | Ensure package manager repositories are configured"
  block:
  - name: "MANUAL| 1.2.2 | Ensure package manager repositories are configured"
    command: yum repolist
    changed_when: no
    register: repolist
    tags:
    - skip_ansible_lint

  - name: "AUDIT| 1.2.2 | Ensure package manager repositories are configured"
    debug:
      msg:
      - "Please check against site policy repos listed below match expected:"
      - "{{ repolist.stdout_lines }}"
  when:
  - amznlnx2cis_rule_1_2_2
  tags:
  - level1
  - notAUTOMATED
  - patch
  - rule_1.2.2
  - skip_ansible_lint

- name: "AUTOMATED | 1.2.3 | PATCH | Ensure gpgcheck is globally activated"
  block:
  - name: "AUTOMATED | 1.2.3 | PATCH | Ensure gpgcheck is globally activated"
    find:
      paths: /etc/yum.repos.d
      patterns: "*.repo"
    register: yum_repos
    changed_when: no

  - name: "AUTOMATED | 1.2.3 | PATCH | Ensure gpgcheck is globally activated"
    replace:
      path: "{{ item.path }}"
      regexp: "^gpgcheck=0"
      replace: "gpgcheck=1"
    loop: "{{ yum_repos.files }}"
  when:
  - amznlnx2cis_rule_1_2_3
  tags:
  - level1
  - AUTOMATED
  - patch
  - rule_1.2.3
