---

- name: "AUTOMATED | 1.8 | PATCH | Ensure updates, patches, and additional security software are installed"
  package:
    name: "*"
    state: latest
  when:
  - amznlnx2cis_rule_1_8
  # - not system_is_ec2
  tags:
  - level1
  - patch
  - rule_1.8
  - skip_ansible_lint
  vars:
    ansible_python_interpreter: /bin/python
