---

- name: "AUTOMATED | 1.4.1 | PATCH | Ensure permissions on bootloader config are configured | Update grub config settings"
  file:
    path: "{{ amznlnx2cis_bootloader_file }}"
    owner: root
    group: root
    mode: 0600
  when:
    - amznlnx2cis_legacy_boot
    - amznlnx2cis_rule_1_4_1
  tags:
    - level1
    - AUTOMATED
    - grub
    - patch
    - rule_1.4.1

- name: "AUTOMATED | 1.4.2 | PATCH | Ensure authentication required for single user mode"
  block:
  - name: "AUTOMATED | 1.4.2 | PATCH | Ensure authentication required for single user mode | Emergency service"
    lineinfile:
      dest: /usr/lib/systemd/system/emergency.service
      regexp: '/sbin/sulogin'
      line: 'ExecStart=-/bin/sh -c "/sbin/sulogin; /usr/bin/systemctl --fail --no-block default'

  - name: "AUTOMATED | 1.4.2 | PATCH | Ensure authentication required for single user mode | Rescue service"
    lineinfile:
      dest: /usr/lib/systemd/system/rescue.service
      regexp: '/sbin/sulogin'
      line: 'ExecStart=-/bin/sh -c "/sbin/sulogin; /usr/bin/systemctl --fail --no-block default'
  when:
    - amznlnx2cis_rule_1_4_2
    - ansible_facts['distribution_major_version'] is version('2', '>=')
  tags:
    - level1
    - patch
    - rule_1.4.2
    - AUTOMATED

- name: debug
  debug:
    msg:
      - "{{ ansible_distribution_major_version }}"
  tags:
    - level1
    - patch
    - rule_1.4.2
    - AUTOMATED
