---

- name: "AUTOMATED | 1.6.1.1 | PATCH | Ensure SELinux is installed"
  package:
    name: libselinux
    state: present
  when:
  - not amznlnx2cis_selinux_disable
  - amznlnx2cis_rule_1_6_1_1
  tags:
  - level1
  - AUTOMATED
  - patch
  - selinux
  - rule_1.6.1.1
  vars:
    ansible_python_interpreter: /bin/python

- name: "AUTOMATED | 1.6.1.2 | PATCH | Ensure SELinux is not disabled in bootloader configuration"
  replace:
    dest: /etc/default/grub
    regexp: '(selinux|enforcing)\s*=\s*0\s*'
  register: selinux_grub_patch
  ignore_errors: yes
  notify: grub2cfg
  when:
  - not amznlnx2cis_selinux_disable
  - amznlnx2cis_rule_1_6_1_2
  tags:
  - level1
  - AUTOMATED
  - patch
  - selinux
  - rule_1.6.1.2

- name: "\n
         AUTOMATED | 1.6.1.3 | PATCH | Ensure SELinux policy is configured\n
         AUTOMATED | 1.6.1.4 | PATCH | Ensure the SELinux state is enforcing or permissive"
  selinux:
    conf: /etc/selinux/config
    policy: "{{ amznlnx2cis_selinux_pol }}"
    state: "{{ amznlnx2cis_selinux_state }}"
  when:
  - not amznlnx2cis_selinux_disable
  - amznlnx2cis_rule_1_6_1_3
  - amznlnx2cis_rule_1_6_1_4
  tags:
  - level1
  - AUTOMATED
  - selinux
  - patch
  - rule_1.6.1.3
  - rule_1.6.1.4

- name: "AUTOMATED | 1.6.1.5 | PATCH | Ensure the SELinux state is enforcing"
  selinux:
    conf: /etc/selinux/config
    policy: "{{ amznlnx2cis_selinux_pol }}"
    state: enforcing
  when:
  - not amznlnx2cis_selinux_disable
  - not amznlnx2cis_selinux_state == "permissive"
  - amznlnx2cis_rule_1_6_1_5
  tags:
  - level2
  - AUTOMATED
  - selinux
  - patch
  - rule_1.6.1.5

- name: "AUTOMATED | 1.6.1.6 | AUDIT | Ensure no unconfined services exist"
  block:
  - name: "AUTOMATED | 1.6.1.6 | AUDIT | Ensure no unconfined services exist | Find the unconfined services"
    shell: ps -eZ | grep unconfined_service_t
    register: amznlnx2cis_1_6_1_6_unconf_services
    failed_when: no
    changed_when: no

  - name: "AUTOMATED | 1.6.1.6 | AUDIT | Ensure no unconfined services exist | Message on no unconfined services"
    debug:
      msg: "Good News! There are no unconfined services found on your system"
    when: amznlnx2cis_1_6_1_6_unconf_services.stdout | length == 0

  - name: "AUTOMATED | 1.6.1.6 | AUDIT | Ensure no unconfined services exist | Message on unconfined services"
    debug:
      msg: "Warning! You have unconfined services: {{ amznlnx2cis_1_6_1_6_unconf_services.stdout_lines }}"
    when: amznlnx2cis_1_6_1_6_unconf_services.stdout | length > 0
  when:
  - amznlnx2cis_rule_1_6_1_6
  tags:
  - level1
  - audit
  - rule_1.6.1.6

- name: "AUTOMATED | 1.6.1.7 | PATCH | Ensure SETroubleshoot is not installed"
  package:
    name: setroubleshoot
    state: absent
  when:
  - amznlnx2cis_rule_1_6_1_7
  tags:
  - level1
  - AUTOMATED
  - selinux
  - patch
  - rule_1.6.1.7
  vars:
    ansible_python_interpreter: /bin/python

- name: "AUTOMATED | 1.6.1.8 | PATCH | Ensure the MCS Translation Service (mcstrans) is not installed"
  package:
    name: mcstrans
    state: absent
  when:
  - amznlnx2cis_rule_1_6_1_8
  tags:
  - level1
  - AUTOMATED
  - patch
  - rule_1.6.1.8
  vars:
    ansible_python_interpreter: /bin/python
